create table if not exists dashboard_registros (
  id bigint generated by default as identity primary key,
  id_teste text unique,
  marca text,
  data_execucao date,
  data_execucao_original text,
  ciclo text,
  plano_teste text,
  teste text,
  resultado_teste text,
  status_teste text,
  responsavel_teste text,
  longa_duracao boolean,
  cliente text,
  stage text,
  row_index integer,
  quality_flags jsonb default '{}'::jsonb,
  dados jsonb default '{}'::jsonb,
  criado_em timestamp with time zone default now(),
  atualizado_em timestamp with time zone default now()
);

alter table dashboard_registros enable row level security;

create policy "Permitir leitura publica dos registros"
on dashboard_registros
for select
to anon
using (true);

create policy "Permitir insert publico dos registros"
on dashboard_registros
for insert
to anon
with check (true);

create policy "Permitir update publico dos registros"
on dashboard_registros
for update
to anon
using (true)
with check (true);
